// biscoitoFrases.js
const frases = [
  "Grandes mudanças começam com pequenas decisões.",
  "A sorte favorece quem age com coragem.",
  "Um novo caminho se abrirá em breve.",
  "Sua persistência trará recompensas.",
  "Boas notícias chegarão quando menos esperar.",
  "A paciência será sua maior aliada.",
  "Um encontro inesperado trará alegria.",
  "Você está mais perto do sucesso do que imagina.",
  "Confie no processo da vida.",
  "Um desafio revelará sua força interior.",

  "A tranquilidade virá após este momento.",
  "O esforço de hoje será o orgulho de amanhã.",
  "Algo bom está se aproximando.",
  "Você colherá o que tem plantado.",
  "A sorte acompanha quem mantém a fé.",
  "Um sonho antigo começará a se realizar.",
  "Sua dedicação não passará despercebida.",
  "O caminho certo se mostrará claro.",
  "Uma oportunidade valiosa surgirá.",
  "Você fará uma escolha acertada.",

  "O equilíbrio trará paz ao seu coração.",
  "Uma resposta chegará no momento certo.",
  "O sucesso será construído passo a passo.",
  "Sua intuição está correta.",
  "Um ciclo positivo está começando.",
  "A calma abrirá portas importantes.",
  "Você está protegido contra energias negativas.",
  "O reconhecimento virá com o tempo.",
  "Uma mudança trará crescimento.",
  "A confiança abrirá novos horizontes.",

  "Você encontrará clareza em breve.",
  "Um gesto sincero trará bons retornos.",
  "A sorte está ao seu lado hoje.",
  "Seu caminho será iluminado.",
  "Uma decisão sábia trará estabilidade.",
  "O aprendizado será recompensador.",
  "Você superará um obstáculo importante.",
  "A perseverança trará vitórias.",
  "Um novo começo se aproxima.",
  "Você encontrará apoio inesperado.",

  "O futuro reserva boas surpresas.",
  "A disciplina trará resultados duradouros.",
  "Uma fase próspera está por vir.",
  "Você atrairá boas oportunidades.",
  "A serenidade guiará suas escolhas.",
  "Um desejo será atendido.",
  "Você alcançará um objetivo importante.",
  "A esperança se renovará.",
  "Um passo ousado valerá a pena.",
  "Você está alinhado com seu propósito.",

  "A sorte acompanhará suas ações.",
  "Um momento de clareza trará decisões firmes.",
  "O esforço constante vencerá.",
  "Uma boa notícia trará alívio.",
  "Você encontrará harmonia em breve.",
  "O tempo trabalhará a seu favor.",
  "Uma escolha trará prosperidade.",
  "Você colherá frutos positivos.",
  "A confiança atrairá sucesso.",
  "Um novo aprendizado será valioso.",

  "A determinação abrirá caminhos.",
  "Você está cercado de boas energias.",
  "Um projeto trará satisfação.",
  "A paciência será recompensada.",
  "Você receberá reconhecimento.",
  "Uma mudança será benéfica.",
  "O equilíbrio trará felicidade.",
  "Você tomará a decisão certa.",
  "A sorte sorrirá para você.",
  "Um novo contato será importante.",

  "Você está evoluindo constantemente.",
  "Uma resposta virá em breve.",
  "O sucesso será consequência da dedicação.",
  "Você encontrará estabilidade.",
  "Uma boa oportunidade surgirá.",
  "O foco trará conquistas.",
  "Você superará dúvidas internas.",
  "A tranquilidade será restaurada.",
  "Um novo ciclo se inicia.",
  "Você se sentirá confiante novamente.",

  "A clareza mental trará progresso.",
  "Você alcançará equilíbrio emocional.",
  "Um momento de sorte se aproxima.",
  "A constância trará vitórias.",
  "Você encontrará soluções simples.",
  "Uma escolha trará paz.",
  "O esforço será reconhecido.",
  "Você receberá boas notícias.",
  "A confiança será renovada.",
  "Um plano dará certo.",

  "Você atrairá prosperidade.",
  "Uma fase positiva começa agora.",
  "A dedicação será recompensada.",
  "Você encontrará respostas internas.",
  "Um gesto correto trará retorno.",
  "A esperança se fortalecerá.",
  "Você terá clareza nas decisões.",
  "Uma oportunidade valiosa aparecerá.",
  "O sucesso está em construção.",
  "Você encontrará apoio sincero.",

  "A paciência abrirá portas.",
  "Você alcançará estabilidade emocional.",
  "Uma escolha consciente trará sucesso.",
  "Você está no caminho certo.",
  "A sorte se manifesta nos detalhes.",
  "Você se sentirá mais seguro.",
  "Um novo desafio trará crescimento.",
  "O equilíbrio guiará seus passos.",
  "Você colherá bons resultados.",
  "Uma resposta positiva chegará.",

  "Você atrairá boas conexões.",
  "Uma decisão firme trará alívio.",
  "O foco trará prosperidade.",
  "Você encontrará tranquilidade.",
  "Uma mudança será favorável.",
  "A persistência vencerá.",
  "Você alcançará clareza.",
  "Um objetivo será atingido.",
  "Você se sentirá realizado.",
  "A sorte estará presente.",

  "Você encontrará estabilidade financeira.",
  "Uma fase de crescimento começa.",
  "A dedicação valerá a pena.",
  "Você tomará boas decisões.",
  "Uma resposta aguardada chegará.",
  "Você se sentirá confiante.",
  "O esforço trará retorno.",
  "Você alcançará harmonia.",
  "Uma oportunidade se revelará.",
  "A sorte caminhará com você.",

  "Você superará inseguranças.",
  "Uma escolha trará prosperidade.",
  "Você encontrará paz interior.",
  "Um novo plano dará certo.",
  "A paciência será recompensada.",
  "Você se sentirá fortalecido.",
  "Uma boa notícia se aproxima.",
  "Você alcançará sucesso.",
  "O equilíbrio trará alegria.",
  "A vida responderá positivamente.",

  "Você atrairá estabilidade.",
  "Uma decisão trará segurança.",
  "Você encontrará clareza emocional.",
  "Um caminho promissor se abrirá.",
  "A sorte recompensará sua dedicação.",
  "Você sentirá confiança renovada.",
  "Uma fase tranquila se aproxima.",
  "Você tomará decisões sábias.",
  "O sucesso virá naturalmente.",
  "Você colherá bons frutos."
];

module.exports = { frases };
